package com.example.schedulebook.domain.deadletter.enums;

public enum DeadLetterSource {
    FORCE_LOGOUT_RETRY_SCHEDULER,
    FORCE_LOGOUT_REDIS_MESSAGE_DELEGATE,
    COMMENT_REDIS_MESSAGE_DELEGATE,
    NOTIFICATION_REDIS_MESSAGE_DELEGATE,
    NOTIFICATION_RETRY_SCHEDULER,
    OUTBOX_TRANSACTION_SERVICE,
    OUTBOX_SERVICE
}
